version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres-python
    restart: always
    environment:
      POSTGRES_USER: eduardo
      POSTGRES_PASSWORD: eduardo
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
